config/routes.rb
Rails.application.routes.draw do
  resources :abbreviations
  resources :brands
  resources :supermarkets
  resources :product_prices

  resources :categories do
    get 'add_product', action: :add_product
  end

  resources :products  do
    get 'add_price', action: :add_price
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/supermarket.rb
class Supermarket < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :product_prices
end

app/controllers/supermarkets_controller.rb
class SupermarketsController < ApplicationController
  before_action :set_supermarket, only: [:show, :edit, :update, :destroy]

  # GET /supermarkets
  # GET /supermarkets.json
  def index
    @supermarkets = Supermarket.all
  end

  # GET /supermarkets/1
  # GET /supermarkets/1.json
  def show
  end

  # GET /supermarkets/new
  def new
    @supermarket = Supermarket.new
  end

  # GET /supermarkets/1/edit
  def edit
  end

  # POST /supermarkets
  # POST /supermarkets.json
  def create
    @supermarket = Supermarket.new(supermarket_params)

    respond_to do |format|
      if @supermarket.save
        format.html { redirect_to @supermarket, notice: 'Supermarket was successfully created.' }
        format.json { render :show, status: :created, location: @supermarket }
      else
        format.html { render :new }
        format.json { render json: @supermarket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supermarkets/1
  # PATCH/PUT /supermarkets/1.json
  def update
    respond_to do |format|
      if @supermarket.update(supermarket_params)
        format.html { redirect_to @supermarket, notice: 'Supermarket was successfully updated.' }
        format.json { render :show, status: :ok, location: @supermarket }
      else
        format.html { render :edit }
        format.json { render json: @supermarket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supermarkets/1
  # DELETE /supermarkets/1.json
  def destroy
    @supermarket.destroy
    respond_to do |format|
      format.html { redirect_to supermarkets_url, notice: 'Supermarket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supermarket
      @supermarket = Supermarket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supermarket_params
      params.require(:supermarket).permit(:name)
    end
end

app/helpers/supermarkets_helper.rb
module SupermarketsHelper
end

app/views/supermarkets/_form.html.erb
<%= form_with(model: supermarket, local: true) do |form| %>
  <% if supermarket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supermarket.errors.count, "error") %> prohibited this supermarket from being saved:</h2>

      <ul>
        <% supermarket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'font-weight-bold' %>
    <%= form.text_field :name, required: true, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/supermarkets/_prices.erb
<% unless product_prices.empty? %>
  <div class="row mb-1">
      <div class="col font-weight-bold">Product</div>
      <div class="col font-weight-bold">Price</div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="w-100"></div>
  </div>
  <% product_prices.each do |product_price| %>
    <div class="row">
      <div class="col"><%= product_price.product.name %></div>
      <div class="col"><%= product_price.price %></div>
      <div class="col"><%= link_to 'Show', product_price %></div>
      <div class="col"><%= link_to 'Edit', edit_product_price_path(product_price) %></div>
      <div class="col"><%= link_to 'Destroy', product_price, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      <div class="w-100"></div>
    </div>
  <% end %>
<% else %>
    <div class="row justify-content-start">
      <div class="col-6">No price has been registred for this supermarket's products yet.</div>
  </div>
<% end %>

app/views/supermarkets/edit.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-6">Editing</h1>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= render 'form', supermarket: @supermarket %>
    </div>
  </div>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= link_to 'Show', @supermarket %> |
      <%= link_to 'List', supermarkets_path %>
    </div>
  </div>
</div>

app/views/supermarkets/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-4">Supermarkets</h1>
  <hr class="my-4">

  <% unless @supermarkets.empty? %>
  <div class="row mb-1">
      <div class="col font-weight-bold">Name</div>
      <div class="col"></div>
      <div class="w-100"></div>
  </div>
  <% @supermarkets.each do |supermarket| %>
    <div class="row">
      <div class="col"><%= supermarket.name %></div>
      <div class="col">
        <div class="row">
          <div class="col"><%= link_to 'Show', supermarket %></div>
          <div class="col"><%= link_to 'Edit', edit_supermarket_path(supermarket) %></div>
          <div class="col"><%= link_to 'Destroy', supermarket, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </div>
      </div>
      <div class="w-100"></div>
    </div>
  <% end %>
<% else %>
    <div class="row justify-content-start">
      <div class="col-6">No supermarket has been registered yet.</div>
    </div>
<% end %>
  <hr class="my-4">

  <div class="row mt-3 justify-content-center">
    <div class="col">
      <%= link_to 'New Supermarket', new_supermarket_path %>
    </div>
  </div>
</div>

app/views/supermarkets/new.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-4">New Supermarket</h1>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= render 'form', supermarket: @supermarket %>
    </div>
  </div>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= link_to 'List', supermarkets_path %>
    </div>
  </div>
</div>

app/views/supermarkets/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-4"><%= @supermarket.name %></h1>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= render 'products/prices', product_prices: @supermarket.product_prices %>
    </div>
  </div>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= link_to 'Edit', edit_supermarket_path(@supermarket) %> |
      <%= link_to 'List', products_path %>
    </div>
  </div>
</div>