config/routes.rb
Rails.application.routes.draw do
  resources :abbreviations
  resources :brands
  resources :supermarkets
  resources :product_prices

  resources :categories do
    get 'add_product', action: :add_product
  end

  resources :products  do
    get 'add_price', action: :add_price
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :add_product]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /categories/1/add_product
  def add_product
    @product = Product.new(category: @category)
    render 'products/new'
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id] || params[:category_id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :validated)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'font-weight-bold' %>
    <%= form.text_field :name, required: true, class: 'form-control' %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :validated, class: 'form-check-input' %>
    <%= form.label :validated, class: 'form-check-label' %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/_products.erb
<% unless products.empty? %>
  <div class="row mb-1">
      <div class="col font-weight-bold">Name</div>
      <div class="col font-weight-bold">Brand</div>
      <div class="col font-weight-bold">Validated</div>
      <div class="col-3"></div>
      <div class="w-100"></div>
  </div>
  <% products.each do |product| %>
    <div class="row">
      <div class="col text-nowrap"><%= product.name %></div>
      <div class="col text-nowrap"><%= product.brand.name %></div>
      <div class="col text-nowrap"><%= product.validated %></div>
      <div class="col-3">
        <div class="row">
          <div class="col"><%= link_to 'Show', product %></div>
          <div class="col"><%= link_to 'Edit', edit_product_path(product) %></div>
          <div class="col"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </div>
      </div>
      <div class="w-100"></div>
    </div>
  <% end %>
<% else %>
    <div class="row justify-content-start">
      <div class="col-6">No product has been registred for this category yet.</div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'List', categories_path %>

app/views/categories/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-4">Categories</h1>
  <hr class="my-4">

  <% unless @categories.empty? %>
  <div class="row mb-1">
      <div class="col font-weight-bold">Name</div>
      <div class="col font-weight-bold">Validated</div>
      <div class="col"></div>
      <div class="w-100"></div>
  </div>
  <% @categories.each do |category| %>
    <div class="row">
      <div class="col"><%= category.name %></div>
      <div class="col"><%= category.validated %></div>
      <div class="col">
        <div class="row">
          <div class="col"><%= link_to 'Show', category %></div>
          <div class="col"><%= link_to 'Edit', edit_category_path(category) %></div>
          <div class="col"><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </div>
      </div>
      <div class="w-100"></div>
    </div>
  <% end %>
<% else %>
    <div class="row justify-content-start">
      <div class="col-6">No category has been registered yet.</div>
    </div>
<% end %>
  <hr class="my-4">

  <div class="row mt-3 justify-content-center">
    <div class="col">
      <%= link_to 'New Category', new_category_path %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-6">New Category</h1>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= render 'categories/form', category: @category %>
    </div>
  </div>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= link_to 'List', categories_path %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-4">Category</h1>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
        <strong>Name:</strong>
    </div>
    <div class="col">
        <%= @category.name %>
    </div>
    <div class="w-100"></div>
    <div class="col">
      <strong>Validated:</strong>
    </div>
    <div class="col">
      <%= @category.validated %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <p class="lead font-weight-bold">Products in this category</p>
      <%= render 'categories/products', products: @category.products %>
    </div>
  </div>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= link_to 'Add Product', category_add_product_path(@category) %> |
      <%= link_to 'Edit', edit_category_path(@category) %> |
      <%= link_to 'List', categories_path %>
    </div>
  </div>
</div>