config/routes.rb
Rails.application.routes.draw do
  resources :abbreviations
  resources :brands
  resources :supermarkets
  resources :product_prices

  resources :categories do
    get 'add_product', action: :add_product
  end

  resources :products  do
    get 'add_price', action: :add_price
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: { scope: :brand }
  validates :validated, inclusion: { in: [ true, false ] }
  validates :category, presence: true
  validates :brand, presence: true
  belongs_to :category
  belongs_to :brand
  has_many :product_prices

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :add_price]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /products/1/add_price
  def add_price
    @product_price = ProductPrice.new(product: @product)
    render 'product_prices/new'
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id] || params[:product_id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :category_id, :brand_id, :validated)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'font-weight-bold' %>
    <%= form.text_field :name, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :category_id, class: 'font-weight-bold' %>
    <%= form.select :category_id,
          options_for_select(Category.all.map{|c| [c.name, c.id]}, product.category_id),
          {},
          {required: true, disabled: !product.category.nil?, class: 'custom-select'}
    %>
    <%= form.hidden_field :category_id unless product.category.nil? %>
  </div>

  <div class="form-group">
    <%= form.label :brand_id, class: 'font-weight-bold' %>
    <%= form.select :brand_id,
          options_for_select(Brand.all.map{|c| [c.name, c.id]}, product.brand_id),
          {},
          {required: true, class: 'custom-select'} %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :validated, class: 'form-check-input' %>
    <%= form.label :validated, class: 'form-check-label' %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/_prices.erb
<% unless product_prices.empty? %>
  <div class="row mb-1">
      <div class="col font-weight-bold">Supermarket</div>
      <div class="col font-weight-bold">Price</div>
      <div class="col-3"></div>
      <div class="w-100"></div>
  </div>
  <% product_prices.each do |product_price| %>
    <div class="row">
      <div class="col"><%= product_price.supermarket.name %></div>
      <div class="col"><%= product_price.price %></div>
      <div class="col-3">
        <div class="row">
          <div class="col"><%= link_to 'Show', product_price %></div>
          <div class="col"><%= link_to 'Edit', edit_product_price_path(product_price) %></div>
          <div class="col"><%= link_to 'Destroy', product_price, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </div>
      </div>
      <div class="w-100"></div>
    </div>
  <% end %>
<% else %>
    <div class="row justify-content-start">
      <div class="col-6">No price has been registred for this supermarket's products yet.</div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-4">Editing</h1>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= render 'form', product: @product %>
    </div>
  </div>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= link_to 'Show', @product %> |
      <%= link_to 'List', products_path %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-4">Products</h1>
  <hr class="my-4">

  <% unless @products.empty? %>
  <div class="row mb-1">
      <div class="col font-weight-bold">Name</div>
      <div class="col font-weight-bold">Category</div>
      <div class="col font-weight-bold">Brand</div>
      <div class="col font-weight-bold">Validated</div>
      <div class="col"></div>
      <div class="w-100"></div>
  </div>
  <% @products.each do |product| %>
    <div class="row">
      <div class="col"><%= product.name %></div>
      <div class="col"><%= product.category.name %></div>
      <div class="col"><%= product.brand.name %></div>
      <div class="col"><%= product.validated %></div>
      <div class="col">
        <div class="row">
          <div class="col"><%= link_to 'Show', product %></div>
          <div class="col"><%= link_to 'Edit', edit_product_path(product) %></div>
          <div class="col"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </div>
      </div>
      <div class="w-100"></div>
    </div>
  <% end %>
<% else %>
    <div class="row justify-content-start">
      <div class="col-6">No product has been registered yet.</div>
    </div>
<% end %>
  <hr class="my-4">

  <div class="row mt-3 justify-content-center">
    <div class="col">
      <%= link_to 'New Product', new_product_path %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-4">New Product<%== " in #{@product.category&.name}" unless @product.category.nil? %></h1>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= render 'products/form', product: @product %>
    </div>
  </div>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= link_to 'List', products_path %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="display-4">Product</h1>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
        <strong>Name:</strong>
    </div>
    <div class="col">
        <%= @product.name %>
    </div>
    <div class="w-100"></div>
    <div class="col">
      <strong>Category:</strong>
    </div>
    <div class="col">
      <%= link_to @product.category.name, @product.category %>
    </div>
    <div class="w-100"></div>
    <div class="col">
      <strong>Brand:</strong>
    </div>
    <div class="col">
      <%= link_to @product.brand.name, @product.brand %>
    </div>
    <div class="w-100"></div>
    <div class="col">
      <strong>Validated:</strong>
    </div>
    <div class="col">
      <%= @product.validated %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <p class="lead font-weight-bold">Product prices</p>
      <%= render 'products/prices', product_prices: @product.product_prices %>
    </div>
  </div>
  <hr class="my-4">

  <div class="row mt-3">
    <div class="col">
      <%= link_to 'Add Price', product_add_price_path(@product) %> |
      <%= link_to 'Edit', edit_product_path(@product) %> |
      <%= link_to 'List', products_path %>
    </div>
  </div>
</div>